### ISSUE TITLE
SRTM filename format regex bug

### ISSUE THREAD

**Issue by MaRaSu** [ajnisbet/opentopodata#104]
After earlier discussion (issue #90) I renamed my Finland 2m DEM tiles to SRTM like filenames e.g. 

`N4312E.tif` became `N4312E_N6870000E416000.tif`. This worked well for +99% of files and it took quite some time for me to spot the problem: elevation values were `null` for some coordinates. Issue is in the `config.py / _filename_to_tile_corner` regex for northing and easting: in the example above it matches `northing_str = n4312` because of the original filename having `N<digits>E`.

I made a quick fix to regex for myself, with assumption that SRTM northing & easting are always just before the file extension.

**Comment by ajnisbet** [comment]
Oh wow, that must've been a frustrating bug to track down, sorry about that! This is fixed by https://github.com/ajnisbet/opentopodata/commit/13f7541fc2c98f1c6e12bc97272fb353d0d99a92 and is live in the **develop** branch now.

**Comment by MaRaSu** [comment]
@ajnisbet luckily few of my users contributed info about places where elevation profiles did not work. Once I learned which DEM-tiles were failing it was a quick job hunting down the bug & doing the fix. As a user of this great OSS project I'm just happy to be able to contribute back a bit.
