### ISSUE TITLE
Wrong URL for ASTER dataset on the homepage

### ISSUE THREAD

**Issue by l3u** [ajnisbet/opentopodata#14]
This is not related to the server itself, but opentopodata.org:

https://www.opentopodata.org/datasets/aster/ says:

The Open Topo Data public API lets you query ASTER GDEM 30m for free:
    curl https://api.opentopodata.org/v1/srtm30m?locations=57.688709,11.976404

I think this should be
    curl https://api.opentopodata.org/v1/aster30m?locations=57.688709,11.976404

as with `srtm30m`, one gets results from the 30 m SRTM dataset.

Maybe, you want to fix this :-)

**Comment by ajnisbet** [comment]
Thanks for catching that!
