### ISSUE TITLE
Document storage-size requirements of each data set

### ISSUE THREAD

**Issue by janusw** [ajnisbet/opentopodata#16]
It's great that OpenTopoData supports such a great variety of different data sets. However, for someone wanting to host his own server (with one or several of these data sets), a limiting factor might be the storage size needed for the data. Therefore it would be great if the documentation would include the storage-size requirements for each data set.

This information could either be included on the pages that describe the data sets in detail (maybe it is already there for some of them?) and/or it could be included in the summary table on the introduction page.

Since https://www.opentopodata.org/notes/cloud-storage/ mentions the recommendation to convert the data to cloud-optimized GeoTIFF format (COG), it might be useful to document the storage size of the data both in the original format as well as COG.

**Comment by ajnisbet** [comment]
Yep good suggestion,  this has been on my todo list as someone else has asked for it, added as [opentopodata.org/notes/dataset-sizes/](https://www.opentopodata.org/notes/dataset-sizes/) in https://github.com/ajnisbet/opentopodata/commit/e88a5723f5478887a8041a615353362696acdcc5.

Unfortunately I didn't record the "true" dataset sizes before I processed them, so I put the compressed sizes as a standalone page to give a rough sense of how much server you'd need to host them.

The COG format shouldn't increase the size very much, so the sizes should still be valid.

**Comment by janusw** [comment]
That was quick :) Thanks!
