### ISSUE TITLE
(Windows) %(ENV_N_UWSGI_THREADS)s' cannot be expanded.

### ISSUE THREAD

**Issue by 8m0** [ajnisbet/opentopodata#42]
I have this error when trying to **docker run --rm -it --volume C:/path/to/opentopodata/data:/app/data:ro -p 5000:5000 opentopodata sh -c "/usr/bin/supervisord -c /app/docker/supervisord.conf"**:

`Error: Format string '/usr/local/bin/uwsgi --ini /app/docker/uwsgi.ini --processes %(ENV_N_UWSGI_THREADS)s' for 'program:uwsgi.command' contains names ('ENV_N_UWSGI_THREADS') which cannot be expanded. Available names: ENV_CURL_CA_BUNDLE, ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_PATH, ENV_PWD, ENV_PYTHON_GET_PIP_SHA256, ENV_PYTHON_GET_PIP_URL, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_TERM, group_name, here, host_node_name, process_num, program_name in section 'program:uwsgi' (file: '/app/docker/supervisord.conf')
For help, use /usr/bin/supervisord -h`

**Comment by ajnisbet** [comment]
Thanks, `%(ENV_N_UWSGI_THREADS)` is newer than the windows instructions, I'll update them.
