### ISSUE TITLE
Non docker hosting server on windows

### ISSUE THREAD

**Issue by vutle** [ajnisbet/opentopodata#50]
Hi Andrew,

Do you have any document to run the hosting server on windows machine?  I have problem installing the pylibmc.   Also because the windows server machine is virtualized, so we can't host it as a docker app.

thanks

**Comment by vutle** [comment]
Please ignore this.  I got it to work running on a tornado python server.

**Comment by ajnisbet** [comment]
Glad you got it working!

For anyone searching for this in the future, there's a couple of documents that might help:

* [Running Open Topo Data on Windows
](https://www.opentopodata.org/notes/windows-support/)
* [Running without Docker
](https://www.opentopodata.org/notes/running-without-docker/)


These documents are largely contributed by users, as I don't have the ability to test on windows or the patience to run geospatial python projects without docker!
