### ISSUE TITLE
API endpoint for querying the available datasets

### ISSUE THREAD

**Issue by janusw** [ajnisbet/opentopodata#54]
Carrying over a point from https://github.com/ajnisbet/opentopodata/issues/47#issuecomment-900861059:

> Btw, another useful addition for the /health endpoint might be to list the available datasets (which, apart from the version, can be another major difference in how different instances of OTD behave).

And yes, the datasets are listed in config.yaml, so of course they are obvious to the server admin, but in general not to all end users.

This information could be included in the `/health` endpoint or it could go into a new endpoint like `/datasets` or similar.

**Comment by naught101** [comment]
Agreed, this would be super useful.

**Comment by janusw** [comment]
Pretty cool, thanks for taking care of this! :D
