### ISSUE TITLE
What's total size when all datasets are downloaded?

### ISSUE THREAD

**Issue by krtschmr** [ajnisbet/opentopodata#64]
OpenElevation requires around 22GB of storage (https://github.com/Jorl17/open-elevation/blob/master/docs/host-your-own.md) to have all data available, what's the total data required for his beautiful project?

**Comment by ajnisbet** [comment]
OpenTopoData supports many different datasets, including the same 90m SRTM dataset used by OpenElevation. So the storage space depends on which dataset you decide to download.

There's a list in the documentation of all the dataset sizes: https://www.opentopodata.org/notes/dataset-sizes/

OpenTopoData supports many different forms of data compression. This is why [srtm90m](https://www.opentopodata.org/datasets/srtm/) is listed as 12GB for OpenTopoData but 22GB on OpenElevation: it's the same exact data (so you should get the same results, but the instructions I provide for downloading the data includes more efficient compression.

**Comment by krtschmr** [comment]
suggestion: let's write that somewhere in the README.

thanks for explanation!

**Comment by ajnisbet** [comment]
Yeah I know the README is pretty minimal and hard for people who find the project from github: but I want to have all the documentation in one place (opentopodata.org)
