### ISSUE TITLE
Usage in Commercial Applications

### ISSUE THREAD

**Issue by TimMcCauley** [ajnisbet/opentopodata#69]
Thank you for this outstanding library.

I'd be interested to learn about using the different sources of elevation in terms of commercial applications. Is there a compiled list somewhere you can recommend that would help me on this topic? Whilst the Mapzen source looks quite promising, it feels a bit risky to plug and play without doing some research in the first place.

Thanks a bunch and cheers!

**Comment by ajnisbet** [comment]
Hey @TimMcCauley this is a good question!

I don't have any documentation about dataset licensing: I'm not a lawyer, and everyone's situation is different so it's hard for me to assess. But I can give some pointers!

There's kinda three different groups of datasets:

* Some datasets come with zero restrictions, so you can do whatever you want with them. This is mostly seen with datasets (and I think all IP in general) from the US government, so SRTM and 3DEP.
* Many datasets are licensed under  a creative commons attribution license (like CC-BY-4.0) or a license that is largely compatible (like the UK or Canadian Open Government Licenses). The main deal with these licenses is that attribution is required. You are free to modify and sell the data. In addition to these open licenses, many datasets with custom copywrite licensing also allow modification and commercialisation, and require attribution.
* Then there's a whole bunch of other custom licenses with weird restrictions. These are actually pretty rare to come across: the general (though not universal!) philosophy behind governments creating these expensive elevation datasets is for people and businesses to use them for research and development, to provide value for those living within the dataset bounds!

I would like to do better documenting the licensing of opentopodata sources, but for now the [dataset list](https://www.gpxz.io/credit) for the GPXZ elevation API lists a bunch of datasets with links to their licenses. I have done my best effort to ensure that the datasets in GPXZ allow for modification and commercialisation.

Mapzen (like GPXZ) is a "meta" dataset made up of multiple sources. You would need to comply with not only any Mapzen license terms (I don't think there are any) but also the license terms of the sources, which will change depending on the region you are querying. Somewhere out there is a dataset with polygon outlines of the individual sources in mapzen: so the proper way to approach mapzen would be using that dataset to check the licensing requirements of the data you use. I appreciate this is very onerous and opentopodata is rather unhelpful in this pursuit: my excuse is that opentopodata is more of a software which end-users are responsible for configuring, while GPXZ does exactly state attribution and licensing for the data I use.

Does that help? Let me know if there's any more light I can shed on this!

**Comment by TimMcCauley** [comment]
Many thanks for this comprehensive response @ajnisbet this helps heaps - I am going to have a look at the links you provided.
