### ISSUE TITLE
Include example usage from pandas / python

### ISSUE THREAD

**Issue by michaelfeil** [ajnisbet/opentopodata#75]
Thanks for the awesome project.

I wrote the following utility which helped me query some elevation data.
https://gist.github.com/michaelfeil/6d9b5dc41fd09afaa5c2f08c15808036

I could imagine contributing it as "docs" or "example", if there is interest from your side.

**Comment by ajnisbet** [comment]
Thanks for sharing this! I don't have a great place to put code examples at the moment, but I'm grateful to have it linked from here!
