### ISSUE TITLE
Include Dutch 0.5 meter data? (Netherlands / Europe)

### ISSUE THREAD

**Issue by mrAceT** [ajnisbet/opentopodata#79]
Is this data interesting for you to add?

https://service.pdok.nl/rws/ahn/atom/dsm_05m.xml

**Comment by ajnisbet** [comment]
Thanks for letting me know about this dataset!

Unfortunately the public api.opentopodata.org server is nearly full, so I don't have plans to add new datasets, especially high-resolution ones like this.

If anyone gets a self-hosted opentopodata instance working with this dataset though, I'd love to share their steps!
