### ISSUE TITLE
adding ArcticDEM

### ISSUE THREAD

**Issue by ArcticSnow** [ajnisbet/opentopodata#83]
Hi, 
A suggestion: are you aware of the global ArcticDEM?
https://www.pgc.umn.edu/data/arcticdem/

This may be interesting to add to the catalogue.
Thanks

**Comment by ajnisbet** [comment]
Thanks for the suggestion!

Unfortunately ArcticDEM is a rather large dataset and there's no more room on the public API server for more datasets.

But it is still possible to self-host ArcticDEM with opendopodata: while the tile naming scheme of the dataset's files doesn't play nicely with the SRTM format opentopodata expects, it's still possible to use the dataset with a VRT by following the same instructions as EUDEM: https://www.opentopodata.org/datasets/eudem/
