### ISSUE TITLE
API blocking fetch requests

### ISSUE THREAD

**Issue by carsonsaldanha** [ajnisbet/opentopodata#9]
I'm trying to implement the API by fetching the JSON via JavaScript's fetch API or jQuery, but I'm getting an error that access to fetch the API has been "blocked by CORS policy," which usually indicates that the end site is blocking fetch requests.
![Screenshot 2020-08-09 at 3 47 27 PM](https://user-images.githubusercontent.com/68826492/89741581-0b502380-da58-11ea-9615-98c6a89c6c2e.png)

Am I doing something wrong or is this as intended?

**Comment by ajnisbet** [comment]
Hey, thanks for raising this! 

The open software in this repo has full support for browser-based fetch requests and CORS policy. However, the free instance I'm hosting at [api.opentopodata.org](https://api.opentopodata.org/) is configured to block cross-origin requests. These requests effectively bypass the per-IP rate limit, and I want to make sure the server has enough capacity for everyone!

So there are a couple of options to get this working:

* Host [ajnisbet/opentopodata](https://github.com/ajnisbet/opentopodata/) on your own server with CORS enabled
* Proxy requests from api.opentopodata.org through your own server, adding the appropriate CORS header
* If you're working on academic research or a small non-commercial project, send me an email and I can add you to a whitelist on the public api.
