### ISSUE TITLE
Question: performance challenge with FI 2m DEM via VRT

### ISSUE THREAD

**Issue by MaRaSu** [ajnisbet/opentopodata#90]
First: thanks for developing and open sourcing OpenTopoData - great documentation, very easy to set-up.

I'm using a high resolution Finland DEM data with 2m grid. I built a VRT for the data set which is in Finnish ETRS-TM35FIN CRS, tiles are 3k x 3k with LZW compression, biggest tiles over 25MB.

I'm feeding to elevation API coordinates from a route planner (just a little less dense than a GPX track would be) so coordinates are close to each other and many / most for my test cases should fit a single tile. My challenge is the performance: for 95 coordinates (which is my chunking threshold) I get about 12 - 15sec response time on my 6 core (Intel 8700K) / 64GB / data on fast HDD server, when using my other test server a low end 2vCPU 2GB cloud server with cloud SSD I'm getting for same data a 26sec response time. Single coordinate on faster server is about 460ms, 10 coordinates 1663ms.

I would be very grateful for ideas how to improve the performance. Is the VRT / CRS / tile format the cause for the dramatically lower performance than the benchmark in the documentation pages?

**Comment by MaRaSu** [comment]
@ajnisbet very much appreciate your super fast reply with detailed instructions. Your guess on VRT being the problem was indeed spot on. I tested with a single renamed tile, queried with 95 coordinates, response came back in ~360ms with my faster server. I also tested (just to be sure) the elevation values for those same 95 coords - small differences between vrt vs. no-vrt approach (range -0.21m to 0.47m, mean 0.03m, median 0.01m, std deviation 0.11m so good for my needs).

Now I just need to build a little script to do the renaming. I somehow recall seeing something like that either in docs or in some issue discussion? Anyways, I can get it sorted one way or another. Again, thanks for your support!

It was also good to learn that GDAL is having the problem with VRT performance. I'm using quite a bit of other data in Finnish ETRS-TM35FIN as VRT because it is convenient - but apparently not very performant!

**Comment by MaRaSu** [comment]
@ajnisbet it would, but it would have to be separate for northing and easting (for Finnish 2m DEM there is an offset of 2000 only for the easting, northing is based on 0).

And absolutely no need to feel sorry or bad for anything! You have done quite some heavy lifting to create OpenTopoData, hopefully the rest of us can contribute a bit into further enhancing it - and with OSS one can always customize / extend it as needed (BTW very easy to understand code with helpful comments).

**Comment by ajnisbet** [comment]
Ok good point about the differing offsets, I also don't want to support `tile_size_x` and `tile_size_y`, would rather put the effort into other features!

And thank you!

**Comment by MaRaSu** [comment]
@ajnisbet Ok, understood. Anyways I made a fork (tile_size_offset branch) with a code change for supporting `tile_size_offset_x`and `tile_size_offset_y` dataset params, I can turn that to a PR if it makes sense. Though I do not know how common is this practise of having tile bounds not be divisible with tile size.

**Comment by ajnisbet** [comment]
This would probably need all of

```
tile_size_offset_x
tile_size_offset_y
tile_size_x
tile_size_y
```

and I think would only help a small number of usecases. Closing in favour of https://github.com/ajnisbet/opentopodata/issues/91
