### ISSUE TITLE
Improve arbitrary dataset performance

### ISSUE THREAD

**Issue by ajnisbet** [ajnisbet/opentopodata#91]
Gdal is slow at reading VRTs with lots of files.

Unfortunately, using a VRT file is the only way opentopodata supports datasets without SRTM-style file naming, which is a bad experience for users.

Some options [of things to do for datasets which have more than one file and no SRTM style filenames]:

* Build our own spatial index in memory.
  * ✅ Fastest response times
  * ✅ Supports mixed projection (will support any combination of raster files: just need to pick a common projection for the spatial index)
  * ❌ Will massively increase startup time (as have to read the header of every file to determine bounds)
  * ❌ I'll have to make decisions about e.g., how to order files with overlapping bounds, rather than relying on a standard.
* Make a tool for [nested vrts](https://lists.osgeo.org/pipermail/gdal-dev/2015-September/042723.html)
  * ✅ No modifications to opentopodata needed.
  * ✅ The tool would be useful for other projects like [gpxz](https://www.gpxz.io/)
  * ❌ More work than a utility function in opentopodata
  * ❌ It's pretty hacky (might have issues with e.g., filesystem paths)
  * ❌ Slowest response time solution (gdal still has to read 2 or 3 VRTs, and do dozens of bounds comparisons)
  * ❌ VRT restrictions (no mixed projections)
* Parse VRTs in opentopodata (detect when a dataset contains a single vrt file; manually parse it on startup; use that to build a spatial index or honestly just a list of bounds would be faster than gdal)
  * ✅ Transparent for user
  * ✅ Can fallback to regular (slow) mode if any issues are found.
  * ✅ Fast startup and response time
  * ❌ Parsing a VRT might be more complicated than I'm imagining
  * ❌ VRT restrictions (no mixed projections)
  * ❌ If the VRT is updated on disk after startup, should opentopodata's cached spatial index update?

**Comment by shashi4u** [comment]
For parsing the vrt we can generate a python data class VRTDataset from the XSD scheme of vrt
We can use something like **generateDS** python package for this.

VRT Schema from GDAL
https://raw.githubusercontent.com/OSGeo/gdal/master/frmts/vrt/data/gdalvrt.xsd

**Comment by ajnisbet** [comment]
The latest version of opentopodata supports [GTI](https://gdal.org/en/latest/drivers/raster/gti.html#raster-gti) tile indices.

You can build these with GDAL 3.9+ using [gdaltindex](https://gdal.org/en/latest/programs/gdaltindex.html) in place of gdalbuildvrt. The files have proper spatial indexing, so are really fast for large number of files!

Migrating VRTs to GTI indices resolves essentially all the large dataset performance issues I've had with opentopodata.
